### ISSUE TITLE
Missing Short Codes?

### ISSUE THREAD

**Issue by HDVinnie** [ben182/laravel-auto-translate#9]
```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Return value of Stichoza\GoogleTranslate\GoogleTranslate::translate() must be of the type string, null returned

  at /var/www/html/vendor/stichoza/google-translate-php/src/GoogleTranslate.php: 235
  231:         }
  232: 
  233:         // Check if translation exists
  234:         if (!isset($responseArray[0]) || empty($responseArray[0])) {
  235:             return null;
  236:         }
  237: 
  238:         // Detect languages
  239:         $detectedLanguages = [];
  240: 

  Exception trace:

  1   Stichoza\GoogleTranslate\GoogleTranslate::translate("About")
      /var/www/html/vendor/ben182/laravel-auto-translate/src/Translators/SimpleGoogleTranslator.php : 32

  2   Ben182\AutoTranslate\Translators\SimpleGoogleTranslator::translate("About")
      /var/www/html/vendor/ben182/laravel-auto-translate/src/AutoTranslate.php : 65

  Please use the argument -v to see more details.
```

```
    'target_language' => ['ar', 'bg', 'bn', 'cn', 'cs', 'da', 'de', 'en', 'es', 'et', 'ir', 'fr', 'gr', 'it', 'nl', 'pl', 'pt', 'br', 'ro', 'ru', 'tr', 'tw'],
```

It appears to have failed `php artisan autotrans:all` at `ro` with the error above.

However `ro` is correct for Romanian

**Comment by ben182** [comment]
I will look after this

**Comment by ben182** [comment]
Are other translations working in ro? Or was it just "About"?

**Comment by HDVinnie** [comment]
`About` was the first key in the `en` lang file. But I dont think it comes down to the word. No matter what `word` I try using, if `ro` is target lang it fails. 

I have been doing one file at a time to try and avoid that rate limit.

**Comment by HDVinnie** [comment]
Thinking maybe its a issue with the API package you use? As it works on google site.

https://translate.google.com/#view=home&op=translate&sl=auto&tl=ro&text=About

**Comment by ben182** [comment]
Hi @HDVinnie 
so I checked if the Romanian translation works and it does. However I did some debugging and the translator always fails at the "br" translation. I checked it at google and "br" does not exist as a language code. So this is the cause of the bug. I will improve the package by providing a better exception
